
/*
Code Challenge (Look and Say)

Find the n’th term in Look-and-say (Or Count and Say) Sequence. 
The look-and-say sequence is the sequence of the below integers:
1, 11, 21, 1211, 111221, 312211, 13112221, 1113213211, …

The first term is "1"
Second term is "11", generated by reading first term as "One 1"
(There is one 1 in previous term)
Third term is "21", generated by reading second term as "Two 1"
Fourth term is "1211", generated by reading third term as "One 2 One 1"
and so on

How to find n’th term?

Example:

Input: n = 3
Output: 21
Input: n = 5 
Output: 111221

Regards!
 */


public class MyClass {
  public static void main(String args[]) {
    int n = 10;
    System.out.println(countAndSay(n));
  }
  
  public static String countAndSay(int n) {
        if(n <= 0) return "";
        
        String result = "1";
        for (int i=1; i < n;i++)
        { 
           result = getNextSequence(result);
        }

        
        return result;
    }
    
    public static String getNextSequence(String sequence) {
        StringBuilder nextSequence = new StringBuilder();
        int count = 1;
        char currentChar = sequence.charAt(0);
        
        for(int i=1; i < sequence.length(); i++) {
            if(sequence.charAt(i) == currentChar) {
                count++;
            } else {
                nextSequence.append(count).append(currentChar);
                currentChar = sequence.charAt(i);
                count = 1;
                
            }
        } 
        nextSequence.append(count).append(currentChar);
        
        
        return nextSequence.toString();
    }
}
